### ISSUE TITLE
Error: Provisioning could not be completed...

### ISSUE THREAD

**Issue by pgdrews** [SharePoint/sp-provisioning-service#377]
Strange issue I've not run into before. I get an error of "In order to provision the template you need Tenant Admin rights. Please ask a Tenant Admin to provision the template for you or to promote yourself to a Tenant Admin." when provisioning the Learning Pathways on a new tenant.

I created a new E5 dev tenant last week, and I am the GA of the tenant. I made sure to create the app catalog and then waited over the weekend to attempt to create the Learning Pathways from Look Book. I had no issues using the PnP provisioning for other Look book templates. I validated that I'm an admin for the app catalog.

I created another Global Admin user, and added as admin of the App Catalog, and still get same results trying to provision from the Look Book.

If I do the manual provisioning steps of creating a communication site, and then adding the Customlearning.sppkg, and then running the M365lpConfiguration.ps1 script, followed by opening the CustomLearningAdmin.aspx file....all completes as expected. However, that method doesn't give you a nice finished/policed LP site like the PnP Look Book method.

Is there something I'm missing or is there an issue with Look Book provisioning for this today? I've done this multiple times in different tenants recently without issue and at a bit of a loss. Thanks!

Patrick

![image](https://user-images.githubusercontent.com/7563343/104964946-28900300-59a3-11eb-9c91-db7c754c591f.png)

**Comment by pgdrews** [comment]
Is there any chance its related to this M365 service health advisory that was just posted?

![image](https://user-images.githubusercontent.com/7563343/104966836-84f52180-59a7-11eb-9569-9caf73e810c2.png)

**Comment by PaoloPia** [comment]
Hi,
The issue that you are referring to shouldn't be related to the problem that you are experiencing. I would suggest you to try using a new browsing session (in incognito) just to be sure that it is not a client-caching issue. Eventually, you can press F12 in the browser and investigate the content of the JSON response for the validation request (CanProvisionPackage). Please let me know about your findings. Thanks.

**Comment by pgdrews** [comment]
He @PaoloPia - I even tried this from a completely different PC with a Private EDGE browsing session and still same results. 

Doing an F12 this is what I see for information.  There are no errors, but I think this was the CanProvision you were referencing?

![image](https://user-images.githubusercontent.com/7563343/105050143-178ed280-5a33-11eb-8bc2-2a8fe6e0aea1.png)

**Comment by PaoloPia** [comment]
Could you please expand the array of issues? I see there is one item, and I'd like to see the exception in there. Thx.

**Comment by pgdrews** [comment]
Sure.

![image](https://user-images.githubusercontent.com/7563343/105058902-55442900-5a3c-11eb-8ed9-2bee9107e12c.png)

**Comment by pgdrews** [comment]
And...just to validate that I am a GA and admin on the App Catalog as well.  I've added SPAdmin role too, but that is irrelevant.  

![image](https://user-images.githubusercontent.com/7563343/105059253-b0761b80-5a3c-11eb-846b-b7f85258c803.png)

![image](https://user-images.githubusercontent.com/7563343/105059399-da2f4280-5a3c-11eb-8f44-bdd938feeb8e.png)

**Comment by PaoloPia** [comment]
Excellent, based on the detailed exception that you provided, I can see where the permission check fails. Could you please use the Graph Explorer (https://developer.microsoft.com/en-us/graph/graph-explorer) logged in with the account that you are using for provisioning and execute the following request:

https://graph.microsoft.com/v1.0/me/memberOf?$select=id,displayName

That is exactly what we do in the validation rule, and we check for the existence of an item (which should be the very first one in the resulting array) with displayName="Company Administrator". The result should be something like:

{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#directoryObjects(id,displayName)",
    "value": [
        {
            "@odata.type": "#microsoft.graph.directoryRole",
            "id": "916fb764-3944-41b9-8c15-9c791ce083cd",
            "displayName": "Company Administrator"
        },
       ....

Thanks,
Paolo

**Comment by Kingjaiyee** [comment]
I have this same scenario and the GET Command Above gives this output
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#directoryObjects(id,displayName)",
    "value": [
        {
            "@odata.type": "#microsoft.graph.directoryRole",
            "id": "fa669323-be28-4868-a711-90870266cea1",
            "displayName": null
        },
        {
            "@odata.type": "#microsoft.graph.group",
            "id": "cbaa2604-aaf5-4e1c-b8a9-f923d89ee052",
            "displayName": null
        },
        {
            "@odata.type": "#microsoft.graph.group",
            "id": "a5f71bfd-6308-46f6-a97b-4a7a53d9a272",
            "displayName": null
        },
        {
            "@odata.type": "#microsoft.graph.group",
            "id": "cf59864f-96ff-42a7-8143-a3f295358db9",
            "displayName": null
        },
        {
            "@odata.type": "#microsoft.graph.group",
            "id": "8f7a7cad-92c8-49a8-ae7d-54c8d0c441a5",
            "displayName": null
        },
        {
            "@odata.type": "#microsoft.graph.group",
            "id": "e4cfad2c-3ebf-4244-9fe8-513558b14f90",
            "displayName": null
        }
    ]
}
Please help

**Comment by pgdrews** [comment]
@PaoloPia   - I too get all NULL values

![image](https://user-images.githubusercontent.com/7563343/105543535-85e7c500-5cbf-11eb-880d-5390ddc07548.png)

**Comment by pgdrews** [comment]
@PaoloPia - I found the NULL was a result of having consent to READ directory data.  After clicking on the CONSENT button on the Modify Permissions tab, I was able to run the query and see that it shows me as Global Administrator

![image](https://user-images.githubusercontent.com/7563343/105544587-bda33c80-5cc0-11eb-94aa-9746bba69dd6.png)

**Comment by PaoloPia** [comment]
Hi,
Thanks for sharing the result. So it looks like the problem is that the role that we are looking for is "Company Administrator", but in your tenant it is called "Global Administrator". I'm investigating why that happens. In fact, the docs state that in Microsoft Graph the name should be "Company Administrator" (see here: https://docs.microsoft.com/en-us/azure/active-directory/roles/permissions-reference#available-roles). Stay tuned, thanks.

**Comment by PaoloPia** [comment]
Quick update. It looks like something changed on the API side. We're working on it and we'll update ASAP our provisioning engine accordingly to the API changes.

**Comment by pgdrews** [comment]
@PaoloPia  - excellent.  I had a colleague run into this as well today, and it's definitely something on the code side that is not looking at Global Administrator.  Did Microsoft themselves change that from Company Administrator in Graph? 

Anxious for a resolve, since I believe this blocks anyone from doing any new PnP deployments of the Learning Pathways and Success Site.   I've got some backlog for development as well as some customer/clients needs that are now delayed.  

Any escalation to get this fixed would be much appreciated!

**Comment by Raymoncorrea** [comment]
We have the same issue and appreciate if there's an update on the resolution.

**Comment by mrjims1** [comment]
We're also having the same issue.

**Comment by PaoloPia** [comment]
Hi,
This issue should now be solved. Something changed on the AAD/Graph side and we had to update the provisioning engine accordingly. Please try it again and, in case of any failure, please open a new issue providing the PnP Correlation ID. Thanks for your cooperation.

**Comment by pgdrews** [comment]
Thanks @PaoloPia.  I'm in the process of testing, and currently I have got past the validation and currently the provisioning is in process.  Thanks for your help in resolving!

**Comment by mrjims1** [comment]
@PaoloPia Works fine now - Thanks.

**Comment by pgdrews** [comment]
@PaoloPia  - I think there may still be issues, but I'm doing some more troubleshooting.  The provisioning succeeded for me for LP, but then when going into the CustomLearningAdmin.aspx it throws errors and correlation ID's.  Other pages continue to throw errors around the site as well.   So, I'm starting clean and going to try creating again, and will report back errors/details if still exists.

**Comment by pgdrews** [comment]
@PaoloPia - I'm getting a correlation error on the App package deployment in the App Catalog.  I've tried clearing out and deleting everything and tried the provisioning of LP 3 times now.   Thoughts or other info I can collect to provide to you to research further?

Deployment failed.  Correlation ID: 1dbba59f-d07e-0000-78e6-1f20d3c7a7b3

![image](https://user-images.githubusercontent.com/7563343/106156979-ce800200-6147-11eb-8044-d0e5267d728b.png)

**Comment by pgdrews** [comment]
@PaoloPia here are additional error captures.

Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
[SPLoaderError.loadComponentError]:
Failed to load component "c6062b6a-f22c-4475-897b-25081673c54a" (CustomLearningAdminWebPart). Original error: Failed to load URL 'https://tsim365.sharepoint.com/sites/appcatalog/ClientSideAssets/26c9cd9f-db62-49b1-b102-7f0dad281ea0/webpart-m365lpstrings_en-us_5ebf05c87596e5efe5e691d313907759.js' for resource 'M365LPStrings' in component 'c6062b6a-f22c-4475-897b-25081673c54a' (CustomLearningAdminWebPart). The file was not found in the server.

INNERERROR:
Failed to load URL 'https://tsim365.sharepoint.com/sites/appcatalog/ClientSideAssets/26c9cd9f-db62-49b1-b102-7f0dad281ea0/webpart-m365lpstrings_en-us_5ebf05c87596e5efe5e691d313907759.js' for resource 'M365LPStrings' in component 'c6062b6a-f22c-4475-897b-25081673c54a' (CustomLearningAdminWebPart). The file was not found in the server.
CALLSTACK:
Error
    at t [as constructor] (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6a45ef39ba2a14a973246917083942bc.js:1:874013)
    at new t (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6a45ef39ba2a14a973246917083942bc.js:1:1017762)
    at Function.e.buildErrorWithVerboseLog (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6a45ef39ba2a14a973246917083942bc.js:1:1040936)
    at Function.e.buildLoadComponentError (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6a45ef39ba2a14a973246917083942bc.js:1:1036981)
    at https://modern.akamai.odsp.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_en-us_06fb90fbb103ba8a0bb1.js:1:66114

![image](https://user-images.githubusercontent.com/7563343/106165417-b9f43780-6150-11eb-8a18-15fbad3ef948.png)

**Comment by PaoloPia** [comment]
Hi,
These are issues that apparently are not related to the fix we introduced yesterday. I'll ask people involved in LP project to give an eye and provide you feedback. Thanks.

**Comment by pgdrews** [comment]
Thanks @PaoloPia - thought I would try again for giggles today, but app catalog deployment is still failing for LP.  Thanks!

Patrick

**Comment by Raymoncorrea** [comment]
> Hi,
> These are issues that apparently are not related to the fix we introduced yesterday. I'll ask people involved in LP project to give an eye and provide you feedback. Thanks.

Thanks for the information. We haven't tried the deployment yet as it looks like there's still an issue. Please advise when this will be resolved. Thanks.

**Comment by pgdrews** [comment]
Hi @PaoloPia  - is there any update on getting this fixed yet?  Thanks.

**Comment by pgdrews** [comment]
@PaoloPia - disregard.  This is now working for me.   It was an oversight on my side where I found one of my two Admin accounts in my tenant was NOT SCA on the App Catalog site collection.  After resolving, it seems to have resolved the app pkg deployment.  Thanks!!
